[package]
name = "rusjure_parser"
version = "0.0.0"
authors = ["Richard Tich√Ω <tichy@artify.zone>"]
edition = '2021'
repository = "https://github.com/ArtifyCZ/rusjure"

[dependencies]
rusjure_ast = { version = "0.0.0", path = "../ast" }

pest = "2.5"
pest_derive = "2.5"
